 -- a_c_bear_01
    ['perfect_bear_pelt']        = {['name'] = 'perfect_bear_pelt',        ['label'] = 'Bear Pelt',          ['weight'] = 1500, ['type'] = 'item', ['image'] = 'pelt_bear3.png',        ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_bear_pelt']           = {['name'] = 'good_bear_pelt',           ['label'] = 'Bear Pelt',          ['weight'] = 1500, ['type'] = 'item', ['image'] = 'pelt_bear2.png',        ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_bear_pelt']           = {['name'] = 'poor_bear_pelt',           ['label'] = 'Bear Pelt',          ['weight'] = 1500, ['type'] = 'item', ['image'] = 'pelt_bear.png',         ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- a_c_bearblack_01
    ['perfect_black_bear_pelt']  = {['name'] = 'perfect_black_bear_pelt',  ['label'] = 'Black Bear Pelt',    ['weight'] = 1500, ['type'] = 'item', ['image'] = 'pelt_black_bear3.png',  ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_black_bear_pelt']     = {['name'] = 'good_black_bear_pelt',     ['label'] = 'Black Bear Pelt',    ['weight'] = 1500, ['type'] = 'item', ['image'] = 'pelt_black_bear2.png',  ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_black_bear_pelt']     = {['name'] = 'poor_black_bear_pelt',     ['label'] = 'Black Bear Pelt',    ['weight'] = 1500, ['type'] = 'item', ['image'] = 'pelt_black_bear.png',   ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- a_c_boar_01
    ['perfect_boar_pelt']        = {['name'] = 'perfect_boar_pelt',        ['label'] = 'Boar Pelt',          ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_boar_skin3.png',   ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_boar_pelt']           = {['name'] = 'good_boar_pelt',           ['label'] = 'Boar Pelt',          ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_boar_skin2.png',   ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_boar_pelt']           = {['name'] = 'poor_boar_pelt',           ['label'] = 'Boar Pelt',          ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_boar_skin.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- a_c_buck_01
    ['perfect_buck_pelt']        = {['name'] = 'perfect_buck_pelt',        ['label'] = 'Buck Pelt',          ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_buck3.png',        ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_buck_pelt']           = {['name'] = 'good_buck_pelt',           ['label'] = 'Buck Pelt',          ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_buck2.png',        ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_buck_pelt']           = {['name'] = 'poor_buck_pelt',           ['label'] = 'Buck Pelt',          ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_buck.png',         ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- a_c_buffalo_01
    ['perfect_buffalo_pelt']     = {['name'] = 'perfect_buffalo_pelt',     ['label'] = 'Buffalo Pelt',       ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_buffalo3.png',     ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_buffalo_pelt']        = {['name'] = 'good_buffalo_pelt',        ['label'] = 'Buffalo Pelt',       ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_buffalo2.png',     ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_buffalo_pelt']        = {['name'] = 'poor_buffalo_pelt',        ['label'] = 'Buffalo Pelt',       ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_buffalo.png',      ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- a_c_bull_01
    ['perfect_bull_pelt']        = {['name'] = 'perfect_bull_pelt',        ['label'] = 'Bull Pelt',          ['weight'] = 1500, ['type'] = 'item', ['image'] = 'pelt_bull3.png',        ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_bull_pelt']           = {['name'] = 'good_bull_pelt',           ['label'] = 'Bull Pelt',          ['weight'] = 1500, ['type'] = 'item', ['image'] = 'pelt_bull2.png',        ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_bull_pelt']           = {['name'] = 'poor_bull_pelt',           ['label'] = 'Bull Pelt',          ['weight'] = 1500, ['type'] = 'item', ['image'] = 'pelt_bull.png',         ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- a_c_cougar_01
    ['perfect_cougar_pelt']      = {['name'] = 'perfect_cougar_pelt',      ['label'] = 'Cougar Pelt',        ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_cougar3.png',      ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_cougar_pelt']         = {['name'] = 'good_cougar_pelt',         ['label'] = 'Cougar Pelt',        ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_cougar2.png',      ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_cougar_pelt']         = {['name'] = 'poor_cougar_pelt',         ['label'] = 'Cougar Pelt',        ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_cougar.png',       ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- a_c_cow
    ['perfect_cow_pelt']         = {['name'] = 'perfect_cow_pelt',         ['label'] = 'Cow Pelt',           ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_cow3.png',         ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_cow_pelt']            = {['name'] = 'good_cow_pelt',            ['label'] = 'Cow Pelt',           ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_cow2.png',         ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_cow_pelt']            = {['name'] = 'poor_cow_pelt',            ['label'] = 'Cow Pelt',           ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_cow.png',          ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- a_c_coyote_01
    ['perfect_coyote_pelt']      = {['name'] = 'perfect_coyote_pelt',      ['label'] = 'Coyote Pelt',        ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_coyote3.png',      ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_coyote_pelt']         = {['name'] = 'good_coyote_pelt',         ['label'] = 'Coyote Pelt',        ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_coyote2.png',      ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_coyote_pelt']         = {['name'] = 'poor_coyote_pelt',         ['label'] = 'Coyote Pelt',        ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_coyote.png',       ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- a_c_deer_01
    ['perfect_deer_pelt']        = {['name'] = 'perfect_deer_pelt',        ['label'] = 'Deer Pelt',          ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_deer3.png',        ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_deer_pelt']           = {['name'] = 'good_deer_pelt',           ['label'] = 'Deer Pelt',          ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_deer2.png',        ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_deer_pelt']           = {['name'] = 'poor_deer_pelt',           ['label'] = 'Deer Pelt',          ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_deer.png',         ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- a_c_elk_01
    ['perfect_elk_pelt']         = {['name'] = 'perfect_elk_pelt',         ['label'] = 'Elk Pelt',           ['weight'] = 1000, ['type'] = 'item', ['image'] = 'pelt_elk3.png',         ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_elk_pelt']            = {['name'] = 'good_elk_pelt',            ['label'] = 'Elk Pelt',           ['weight'] = 1000, ['type'] = 'item', ['image'] = 'pelt_elk2.png',         ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_elk_pelt']            = {['name'] = 'poor_elk_pelt',            ['label'] = 'Elk Pelt',           ['weight'] = 1000, ['type'] = 'item', ['image'] = 'pelt_elk.png',          ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- a_c_fox_01
    ['perfect_fox_pelt']         = {['name'] = 'perfect_fox_pelt',         ['label'] = 'Redfox Pelt',        ['weight'] = 100,  ['type'] = 'item', ['image'] = 'pelt_fox3.png',         ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_fox_pelt']            = {['name'] = 'good_fox_pelt',            ['label'] = 'Redfox Pelt',        ['weight'] = 100,  ['type'] = 'item', ['image'] = 'pelt_fox2.png',         ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_fox_pelt']            = {['name'] = 'poor_fox_pelt',            ['label'] = 'Redfox Pelt',        ['weight'] = 100,  ['type'] = 'item', ['image'] = 'pelt_fox.png',          ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- a_c_goat_01
    ['perfect_goat_pelt']        = {['name'] = 'perfect_goat_pelt',        ['label'] = 'Goat Pelt',          ['weight'] = 100,  ['type'] = 'item', ['image'] = 'pelt_goat3.png',        ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_goat_pelt']           = {['name'] = 'good_goat_pelt',           ['label'] = 'Goat Pelt',          ['weight'] = 100,  ['type'] = 'item', ['image'] = 'pelt_goat2.png',        ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_goat_pelt']           = {['name'] = 'poor_goat_pelt',           ['label'] = 'Goat Pelt',          ['weight'] = 100,  ['type'] = 'item', ['image'] = 'pelt_goat.png',         ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- a_c_javelina_01
    ['perfect_javelina_pelt']    = {['name'] = 'perfect_javelina_pelt',    ['label'] = 'Javelina Pelt',      ['weight'] = 100,  ['type'] = 'item', ['image'] = 'pelt_javelina3.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_javelina_pelt']       = {['name'] = 'good_javelina_pelt',       ['label'] = 'Javelina Pelt',      ['weight'] = 100,  ['type'] = 'item', ['image'] = 'pelt_javelina2.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_javelina_pelt']       = {['name'] = 'poor_javelina_pelt',       ['label'] = 'Javelina Pelt',      ['weight'] = 100,  ['type'] = 'item', ['image'] = 'pelt_javelina.png',     ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- a_c_moose_01
    ['perfect_moose_pelt']       = {['name'] = 'perfect_moose_pelt',       ['label'] = 'Moose Pelt',         ['weight'] = 1500, ['type'] = 'item', ['image'] = 'pelt_moose3.png',       ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_moose_pelt']          = {['name'] = 'good_moose_pelt',          ['label'] = 'Moose Pelt',         ['weight'] = 1500, ['type'] = 'item', ['image'] = 'pelt_moose2.png',       ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_moose_pelt']          = {['name'] = 'poor_moose_pelt',          ['label'] = 'Moose Pelt',         ['weight'] = 1500, ['type'] = 'item', ['image'] = 'pelt_moose.png',        ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- a_c_ox_01
    ['perfect_ox_pelt']          = {['name'] = 'perfect_ox_pelt',          ['label'] = 'Ox Pelt',            ['weight'] = 1500, ['type'] = 'item', ['image'] = 'pelt_ox3.png',          ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_ox_pelt']             = {['name'] = 'good_ox_pelt',             ['label'] = 'Ox Pelt',            ['weight'] = 1500, ['type'] = 'item', ['image'] = 'pelt_ox2.png',          ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_ox_pelt']             = {['name'] = 'poor_ox_pelt',             ['label'] = 'Ox Pelt',            ['weight'] = 1500, ['type'] = 'item', ['image'] = 'pelt_ox.png',           ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- a_c_panther_01
    ['perfect_panther_pelt']     = {['name'] = 'perfect_panther_pelt',     ['label'] = 'Panther Pelt',       ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_phanter3.png',     ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_panther_pelt']        = {['name'] = 'good_panther_pelt',        ['label'] = 'Panther Pelt',       ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_phanter2.png',     ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_panther_pelt']        = {['name'] = 'poor_panther_pelt',        ['label'] = 'Panther Pelt',       ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_phanter.png',      ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- a_c_pig_01
    ['perfect_pig_pelt']         = {['name'] = 'perfect_pig_pelt',         ['label'] = 'Pig Pelt',           ['weight'] = 300,  ['type'] = 'item', ['image'] = 'pelt_pig3.png',         ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_pig_pelt']            = {['name'] = 'good_pig_pelt',            ['label'] = 'Pig Pelt',           ['weight'] = 300,  ['type'] = 'item', ['image'] = 'pelt_pig2.png',         ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_pig_pelt']            = {['name'] = 'poor_pig_pelt',            ['label'] = 'Pig Pelt',           ['weight'] = 300,  ['type'] = 'item', ['image'] = 'pelt_pig.png',          ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- a_c_pronghorn_01
    ['perfect_pronghorn_pelt']   = {['name'] = 'perfect_pronghorn_pelt',   ['label'] = 'Pronghorn Pelt',     ['weight'] = 800,  ['type'] = 'item', ['image'] = 'pelt_pronghorn3.png',   ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_pronghorn_pelt']      = {['name'] = 'good_pronghorn_pelt',      ['label'] = 'Pronghorn Pelt',     ['weight'] = 800,  ['type'] = 'item', ['image'] = 'pelt_pronghorn2.png',   ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_pronghorn_pelt']      = {['name'] = 'poor_pronghorn_pelt',      ['label'] = 'Pronghorn Pelt',     ['weight'] = 800,  ['type'] = 'item', ['image'] = 'pelt_pronghorn.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- a_c_bighornram_01
    ['perfect_bighornram_pelt']  = {['name'] = 'perfect_bighornram_pelt',  ['label'] = 'Bighornram Pelt',    ['weight'] = 800,  ['type'] = 'item', ['image'] = 'pelt_bighornram.png',   ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_bighornram_pelt']     = {['name'] = 'good_bighornram_pelt',     ['label'] = 'Bighornram Pelt',    ['weight'] = 800,  ['type'] = 'item', ['image'] = 'pelt_bighornram2.png',  ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_bighornram_pelt']     = {['name'] = 'poor_bighornram_pelt',     ['label'] = 'Bighornram Pelt',    ['weight'] = 800,  ['type'] = 'item', ['image'] = 'pelt_bighornram3.png',  ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- a_c_sheep_01
    ['perfect_sheep_pelt']       = {['name'] = 'perfect_sheep_pelt',       ['label'] = 'Sheep Pelt',         ['weight'] = 300,  ['type'] = 'item', ['image'] = 'pelt_sheep3.png',       ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_sheep_pelt']          = {['name'] = 'good_sheep_pelt',          ['label'] = 'Sheep Pelt',         ['weight'] = 300,  ['type'] = 'item', ['image'] = 'pelt_sheep2.png',       ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_sheep_pelt']          = {['name'] = 'poor_sheep_pelt',          ['label'] = 'Sheep Pelt',         ['weight'] = 300,  ['type'] = 'item', ['image'] = 'pelt_sheep.png',        ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- a_c_wolf
    ['perfect_wolf_pelt']        = {['name'] = 'perfect_wolf_pelt',        ['label'] = 'Wolf Pelt',          ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_wolf3.png',        ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_wolf_pelt']           = {['name'] = 'good_wolf_pelt',           ['label'] = 'Wolf Pelt',          ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_wolf2.png',        ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_wolf_pelt']           = {['name'] = 'poor_wolf_pelt',           ['label'] = 'Wolf Pelt',          ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_wolf.png',         ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- a_c_alligator_03
    ['perfect_alligator_pelt']   = {['name'] = 'perfect_alligator_pelt',   ['label'] = 'Alligator Pelt',     ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_alligator3.png',   ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_alligator_pelt']      = {['name'] = 'good_alligator_pelt',      ['label'] = 'Alligator Pelt',     ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_alligator2.png',   ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_alligator_pelt']      = {['name'] = 'poor_alligator_pelt',      ['label'] = 'Alligator Pelt',     ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_alligator.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    -- mp_a_c_alligator_01
    ['legendary_alligator_pelt'] = {['name'] = 'legendary_alligator_pelt', ['label'] = 'Leg Alligator Pelt', ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_legalligator.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    -- mp_a_c_beaver_01
    ['legendary_beaver_pelt']    = {['name'] = 'legendary_beaver_pelt',    ['label'] = 'Leg Beaver Pelt',    ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_legbeaver.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    -- mp_a_c_boar_01
    ['legendary_boar_pelt']      = {['name'] = 'legendary_boar_pelt',      ['label'] = 'Leg Boar Pelt',      ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_legboar.png',      ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    -- mp_a_c_cougar_01
    ['legendary_cougar_pelt']    = {['name'] = 'legendary_cougar_pelt',    ['label'] = 'Leg Cougar Pelt',    ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_legcougar.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    -- mp_a_c_coyote_01
    ['legendary_coyote_pelt']    = {['name'] = 'legendary_coyote_pelt',    ['label'] = 'Leg Coyote Pelt',    ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_legcoyote.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    -- mp_a_c_panther_01
    ['legendary_panther_pelt']   = {['name'] = 'legendary_panther_pelt',   ['label'] = 'Leg Panther Pelt',   ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_legphanter.png',   ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    -- mp_a_c_wolf_01
    ['legendary_wolf_pelt']      = {['name'] = 'legendary_wolf_pelt',      ['label'] = 'Leg Wolf Pelt',      ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_legwolf.png',      ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    -- a_c_raccoon_01
    ['perfect_raccoon_pelt']     = {['name'] = 'perfect_raccoon_pelt',     ['label'] = 'Raccoon Pelt',       ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_raccoon3.png',     ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Perfect (* * *)'},
    ['good_raccoon_pelt']        = {['name'] = 'good_raccoon_pelt',        ['label'] = 'Raccoon Pelt',       ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_raccoon2.png',     ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good (* *)'},
    ['poor_raccoon_pelt']        = {['name'] = 'poor_raccoon_pelt',        ['label'] = 'Raccoon Pelt',       ['weight'] = 500,  ['type'] = 'item', ['image'] = 'pelt_raccoon.png',      ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Poor (*)'},
    
	-- DIENTES / TOOTH 
    ['tooth_aligatorto'] 		 = {['name'] = 'tooth_aligatorto', 	       ['label'] = 'Alligator tooth', 	['weight'] = 100, 	['type'] = 'item', ['image'] = 'tooth_aligatorto.png',  ['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	  ['combinable'] = nil,		['level'] = 0,      ['description'] = 'Alligator tooth.'},
    ['tooth_beart'] 			 = {['name'] = 'tooth_beart', 		       ['label'] = 'Bear tooth', 		['weight'] = 100, 	['type'] = 'item', ['image'] = 'tooth_beart.png', 		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	  ['combinable'] = nil,		['level'] = 0,      ['description'] = 'Bear tooth.'},
    ['tooth_cougarf'] 			 = {['name'] = 'tooth_cougarf', 	       ['label'] = 'Cougar tooth', 	    ['weight'] = 100, 	['type'] = 'item', ['image'] = 'tooth_cougarf.png', 	['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	  ['combinable'] = nil,		['level'] = 0,      ['description'] = 'Cougar tooth.'},
    ['tooth_coyotef'] 			 = {['name'] = 'tooth_coyotef', 	       ['label'] = 'Coyote tooth', 	    ['weight'] = 100, 	['type'] = 'item', ['image'] = 'tooth_coyotef.png', 	['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	  ['combinable'] = nil,		['level'] = 0,      ['description'] = 'Coyote tooth.'},
    ['tooth_foxt'] 				 = {['name'] = 'tooth_foxt', 		       ['label'] = 'Fox tooth', 		['weight'] = 100, 	['type'] = 'item', ['image'] = 'tooth_foxt.png', 		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	  ['combinable'] = nil,		['level'] = 0,      ['description'] = 'Fox tooth.'},
    ['tooth_raccoont'] 			 = {['name'] = 'tooth_raccoont', 	       ['label'] = 'Raccoon tooth', 	['weight'] = 100, 	['type'] = 'item', ['image'] = 'tooth_raccoont.png', 	['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	  ['combinable'] = nil,		['level'] = 0,      ['description'] = 'Raccoon tooth.'},
    ['tooth_snaket'] 			 = {['name'] = 'tooth_snaket', 		       ['label'] = 'Snake tooth', 		['weight'] = 100, 	['type'] = 'item', ['image'] = 'tooth_snaket.png', 	    ['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	  ['combinable'] = nil,		['level'] = 0,      ['description'] = 'Snake tooth.'},
    ['tooth_turtlet'] 			 = {['name'] = 'tooth_turtlet', 	       ['label'] = 'Turtle tooth', 	    ['weight'] = 100, 	['type'] = 'item', ['image'] = 'tooth_turtlet.png', 	['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	  ['combinable'] = nil,		['level'] = 0,      ['description'] = 'Turtle tooth.'},
    ['tooth_wolftooth'] 		 = {['name'] = 'tooth_wolftooth', 	       ['label'] = 'Wolf tooth', 		['weight'] = 100, 	['type'] = 'item', ['image'] = 'tooth_wolftooth.png', 	['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	  ['combinable'] = nil,		['level'] = 0,      ['description'] = 'Wolf tooth.'},
    ['tooth_boarmusk'] 			 = {['name'] = 'tooth_boarmusk',           ['label'] = 'Boar tusk', 		['weight'] = 100, 	['type'] = 'item', ['image'] = 'tooth_boarmusk.png', 	['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	  ['combinable'] = nil,		['level'] = 0,      ['description'] = 'Boar tusk.'},

     -- GARRAS / CLAWS 
    ['claws_armadilloc'] 		= {['name'] = 'claws_armadilloc', 	       ['label'] = 'Armadillo claws', 	['weight'] = 100, 		['type'] = 'item', 		['image'] = 'claws_armadilloc.png', 	['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	  ['combinable'] = nil,		['level'] = 0,      ['description'] = 'Armadillo claws.'},
    ['claws_bearc'] 			= {['name'] = 'claws_beartc', 		       ['label'] = 'Bear claws', 		['weight'] = 100, 		['type'] = 'item', 		['image'] = 'claws_beartc.png', 		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	  ['combinable'] = nil,		['level'] = 0,      ['description'] = 'Claws.'},
    ['claws_cockc'] 			= {['name'] = 'claws_cockc', 		       ['label'] = 'Rooster claws', 	['weight'] = 100, 		['type'] = 'item', 		['image'] = 'claws_cockc.png', 			['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	  ['combinable'] = nil,		['level'] = 0,      ['description'] = 'Claws.'},
    ['claws_eaglet'] 			= {['name'] = 'claws_eaglet', 		       ['label'] = 'Eagle claws', 		['weight'] = 100, 		['type'] = 'item', 		['image'] = 'claws_eaglet.png', 		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	  ['combinable'] = nil,		['level'] = 0,      ['description'] = 'Claws.'},
    ['claws_hawkt'] 			= {['name'] = 'claws_hawkt', 		       ['label'] = 'Hawk claws', 		['weight'] = 100, 		['type'] = 'item', 		['image'] = 'claws_hawkt.png', 			['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	  ['combinable'] = nil,		['level'] = 0,      ['description'] = 'Claws.'},
    ['claws_opossumc'] 			= {['name'] = 'claws_opossumc', 	       ['label'] = 'Opossumc claws', 	['weight'] = 100, 		['type'] = 'item', 		['image'] = 'claws_opossumc.png', 		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	  ['combinable'] = nil,		['level'] = 0,      ['description'] = 'Claws.'},
    ['claws_owlt'] 				= {['name'] = 'claws_owlt', 		       ['label'] = 'Owl claws', 		['weight'] = 100, 		['type'] = 'item', 		['image'] = 'claws_owlt.png', 			['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	  ['combinable'] = nil,		['level'] = 0,      ['description'] = 'Claws.'},
    ['claws_ravenc'] 			= {['name'] = 'claws_ravenc', 		       ['label'] = 'Raven claws', 		['weight'] = 100, 		['type'] = 'item', 		['image'] = 'claws_ravenc.png', 		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	  ['combinable'] = nil,		['level'] = 0,      ['description'] = 'Claws.'},
    ['claws_beartc']            = {['name'] = 'claws_beartc',              ['label'] = 'Bear Claw',         ['weight'] = 500,       ['type'] = 'item',      ['image'] = 'claws_beartc.png',         ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Bear Claw'},
    ['fiber_woolblack']         = {['name'] = 'fiber_woolblack',           ['label'] = 'Black Yarn Fibre',  ['weight'] = 500,       ['type'] = 'item',      ['image'] = 'fiber_woolblack.png',      ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Fibre from an animal'},
    ['tail_bull']               = {['name'] = 'tail_bull',                 ['label'] = 'Bull Tail',         ['weight'] = 500,       ['type'] = 'item',      ['image'] = 'tail_bull.png',            ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Tail of a bull'},
    ['wool']                    = {['name'] = 'wool',                      ['label'] = 'Wool',              ['weight'] = 500,       ['type'] = 'item',      ['image'] = 'wool.png',                 ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Fluffy wool'},
    ['feathers']                = {['name'] = 'feathers',                  ['label'] = 'Feathers',          ['weight'] = 500,       ['type'] = 'item',      ['image'] = 'feathers.png',             ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Bird Feathers'},
   
    -- CUERNOS / HORN
    ['horn_bison'] 			    = {['name'] = 'horn_bison', 		['label'] = 'Bison horn', 		['weight'] = 100, 		['type'] = 'item', 		['image'] = 'horn_bisonhorn.png', 	['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	  ['combinable'] = nil,		['level'] = 0,      ['description'] = 'Horn.'},
    ['horn_bull'] 			    = {['name'] = 'horn_bull', 			['label'] = 'Bull horn', 		['weight'] = 100, 		['type'] = 'item', 		['image'] = 'horn_bullhorn.png', 	['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	  ['combinable'] = nil,		['level'] = 0,      ['description'] = 'Horn.'},
    ['horn_cowh'] 			    = {['name'] = 'horn_cowh', 			['label'] = 'Cow horn', 		['weight'] = 100, 		['type'] = 'item', 		['image'] = 'horn_cowh.png', 		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	  ['combinable'] = nil,		['level'] = 0,      ['description'] = 'Horn.'},
    ['horn_ox'] 			    = {['name'] = 'horn_ox', 			['label'] = 'Angus Bull horn', 	['weight'] = 100, 		['type'] = 'item', 		['image'] = 'horn_oxhorn.png', 		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	  ['combinable'] = nil,		['level'] = 0,      ['description'] = 'Horn.'},
    ['horn_prong'] 			    = {['name'] = 'horn_prong', 		['label'] = 'Pronghorn horn', 	['weight'] = 100, 		['type'] = 'item', 		['image'] = 'horn_pronghornh.png', 	['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	  ['combinable'] = nil,		['level'] = 0,      ['description'] = 'Horn.'},
    ['horn_ram'] 			    = {['name'] = 'horn_ram', 			['label'] = 'Ram horn', 		['weight'] = 100, 		['type'] = 'item', 		['image'] = 'horn_ramhorn.png', 	['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	  ['combinable'] = nil,		['level'] = 0,      ['description'] = 'Horn.'},
    ['horn_buckantler'] 	    = {['name'] = 'horn_buckantler', 	['label'] = 'Buck Antlers', 	['weight'] = 100, 		['type'] = 'item', 		['image'] = 'horn_buckantler.png', 	['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	  ['combinable'] = nil,		['level'] = 0,      ['description'] = 'Horn.'},
    ['horn_elkantler'] 		    = {['name'] = 'horn_elkantler', 	['label'] = 'Elk antler', 		['weight'] = 100, 		['type'] = 'item', 		['image'] = 'horn_elkantler.png', 	['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	  ['combinable'] = nil,		['level'] = 0,      ['description'] = 'Horn.'},

    -- COLAS / TAIL
    ['tail_fox'] 		        = {['name'] = 'tail_fox', 		    ['label'] = 'Fox tail', 		['weight'] = 100, 		['type'] = 'item', 		['image'] = 'tail_fox.png', 		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	  ['combinable'] = nil,		['level'] = 0,      ['description'] = 'Tail.'},
    ['tail_beaver'] 		    = {['name'] = 'tail_beaver', 		['label'] = 'Beaver tail', 		['weight'] = 100, 		['type'] = 'item', 		['image'] = 'tail_beaver.png', 		['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	  ['combinable'] = nil,		['level'] = 0,      ['description'] = 'Tail.'},
    ['tail_chipmunk_c'] 	    = {['name'] = 'tail_chipmunk_c', 	['label'] = 'Chipmunk tail', 	['weight'] = 100, 		['type'] = 'item', 		['image'] = 'tail_chipmunk_c.png', 	['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	  ['combinable'] = nil,		['level'] = 0,      ['description'] = 'Tail.'},
    ['tail_panthere'] 		    = {['name'] = 'tail_panthere', 		['label'] = 'Panther eyes', 	['weight'] = 100, 		['type'] = 'item', 		['image'] = 'tail_panthere.png', 	['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	  ['combinable'] = nil,		['level'] = 0,      ['description'] = 'Tail.'},
    ['tail_lizardl'] 		    = {['name'] = 'tail_lizardl', 		['label'] = 'Lizard foot', 		['weight'] = 100, 		['type'] = 'item', 		['image'] = 'tail_lizardl.png', 	['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	  ['combinable'] = nil,		['level'] = 0,      ['description'] = 'Tail.'},
    ['tail_rabbitpaw'] 		    = {['name'] = 'tail_rabbitpaw', 	['label'] = 'Rabbit foot', 		['weight'] = 100, 		['type'] = 'item', 		['image'] = 'tail_rabbitpaw.png', 	['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	  ['combinable'] = nil,		['level'] = 0,      ['description'] = 'Tail.'},
        
    -- PICOS / BEAK 
    ['beak_bparrotf'] 		    = {['name'] = 'beak_bparrotf', 		['label'] = 'Parrot beak',          ['weight'] = 100, 		['type'] = 'item', 		['image'] = 'beak_bparrotf.png', 			['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	  ['combinable'] = nil,		['level'] = 0,  ['description'] = 'Colorful parrot beak.'},    
    ['beak_quailb'] 		    = {['name'] = 'beak_quailb', 		['label'] = 'Quail beak',           ['weight'] = 100, 		['type'] = 'item', 		['image'] = 'beak_quailb.png', 				['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	  ['combinable'] = nil,		['level'] = 0,  ['description'] = 'Small quail beak in grasslands.'},    
    ['beak_bbirdf'] 		    = {['name'] = 'beak_bbirdf', 		['label'] = 'Cormorant beak',       ['weight'] = 100, 		['type'] = 'item', 		['image'] = 'beak_bbirdf.png', 				['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	  ['combinable'] = nil,		['level'] = 0,  ['description'] = 'Sleek cormorant beak for diving.'},   
    ['beak_boobyf'] 		    = {['name'] = 'beak_boobyf', 		['label'] = 'Red-footed beak',      ['weight'] = 100, 		['type'] = 'item', 		['image'] = 'beak_boobyf.png', 				['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	  ['combinable'] = nil,		['level'] = 0,  ['description'] = 'Distinctive red-footed booby beak.'},   
    ['beak_daruf'] 			    = {['name'] = 'beak_daruf', 		['label'] = 'Crane beak',           ['weight'] = 100, 		['type'] = 'item', 		['image'] = 'beak_daruf.png', 				['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	  ['combinable'] = nil,		['level'] = 0,  ['description'] = 'Slender crane beak near wetlands.'},    
    ['beak_condorf'] 		    = {['name'] = 'beak_condorf', 		['label'] = 'Condor beak',          ['weight'] = 100, 		['type'] = 'item', 		['image'] = 'beak_condorf.png', 			['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	  ['combinable'] = nil,		['level'] = 0,  ['description'] = 'Massive condor beak for scavenging.'},    
    ['beak_pelicanf'] 		    = {['name'] = 'beak_pelicanf', 		['label'] = 'Pelican beak',         ['weight'] = 100, 		['type'] = 'item', 		['image'] = 'beak_pelicanf.png', 			['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	  ['combinable'] = nil,		['level'] = 0,  ['description'] = 'Large pelican beak for scooping fish.'},   
    ['beak_peasantf'] 		    = {['name'] = 'beak_peasantf', 		['label'] = 'Peasant beak',         ['weight'] = 100, 		['type'] = 'item', 		['image'] = 'beak_peasantf.png', 			['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	  ['combinable'] = nil,		['level'] = 0,  ['description'] = 'Unique peasant beak with omnivorous diet.'},   
    ['beak_loonf'] 			    = {['name'] = 'beak_loonf', 		['label'] = 'Common Loon beak',     ['weight'] = 100, 		['type'] = 'item', 		['image'] = 'beak_loonf.png', 				['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	  ['combinable'] = nil,		['level'] = 0,  ['description'] = 'Pointed common loon beak for underwater fishing.'},    
    ['beak_kbirdf'] 		    = {['name'] = 'beak_kbirdf', 		['label'] = 'Blue Heron beak',      ['weight'] = 100, 		['type'] = 'item', 		['image'] = 'beak_kbirdf.png', 				['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	  ['combinable'] = nil,		['level'] = 0,  ['description'] = 'Majestic great blue heron beak near water.'},    
    ['beak_goosef'] 		    = {['name'] = 'beak_goosef', 		['label'] = 'Goose beak',           ['weight'] = 100, 		['type'] = 'item', 		['image'] = 'beak_goosef.png', 				['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	  ['combinable'] = nil,		['level'] = 0,  ['description'] = 'Eagle beak for hunting.'},    
    ['beak_egretf'] 		    = {['name'] = 'beak_egretf', 		['label'] = 'Snowy Egret beak',     ['weight'] = 100, 		['type'] = 'item', 		['image'] = 'beak_egretf.png', 				['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	  ['combinable'] = nil,		['level'] = 0,  ['description'] = 'Hawk beak for swift hunting.'},    
    ['beak_turkeyf'] 		    = {['name'] = 'beak_turkeyf', 		['label'] = 'Turkey beak',          ['weight'] = 100, 		['type'] = 'item', 		['image'] = 'beak_turkeyf.png', 			['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	  ['combinable'] = nil,		['level'] = 0,  ['description'] = 'Owl beak for nocturnal hunting.'},    
    ['beak_seagullf'] 		    = {['name'] = 'beak_seagullf', 		['label'] = 'Seagull beak',         ['weight'] = 100, 		['type'] = 'item', 		['image'] = 'beak_seagullf.png', 			['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	  ['combinable'] = nil,		['level'] = 0,  ['description'] = 'beak.'},    
    ['beak_rspoonf'] 		    = {['name'] = 'beak_rspoonf', 		['label'] = 'Spoonbill beak',       ['weight'] = 100, 		['type'] = 'item', 		['image'] = 'beak_rspoonf.png', 			['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	  ['combinable'] = nil,		['level'] = 0,  ['description'] = 'Specialized spoonbill beak.'},     
    ['beak_prairif'] 		    = {['name'] = 'beak_prairif', 		['label'] = 'Prairie Chicken beak', ['weight'] = 100, 		['type'] = 'item', 		['image'] = 'beak_prairif.png', 			['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	  ['combinable'] = nil,		['level'] = 0,  ['description'] = 'Robust prairie chicken beak.'},     
    ['beak_chickenf'] 		    = {['name'] = 'beak_chickenf', 		['label'] = 'Chicken beak',         ['weight'] = 100, 		['type'] = 'item', 		['image'] = 'beak_chickenf.png', 			['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	  ['combinable'] = nil,		['level'] = 0,  ['description'] = 'Chicken beak.'},    
    ['beak_eaglef'] 		    = {['name'] = 'beak_eaglef', 		['label'] = 'Eagle beak',           ['weight'] = 100, 		['type'] = 'item', 		['image'] = 'beak_eaglef.png', 				['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	  ['combinable'] = nil,		['level'] = 0,  ['description'] = 'Eagle beak.'},    
    ['beak_hawkf'] 			    = {['name'] = 'beak_hawkf', 		['label'] = 'Hawk beak',            ['weight'] = 100, 		['type'] = 'item', 		['image'] = 'beak_hawkf.png', 				['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	  ['combinable'] = nil,		['level'] = 0,  ['description'] = 'Hawk beak.'},   
    ['beak_owlf'] 			    = {['name'] = 'beak_owlf', 			['label'] = 'Owl beak',             ['weight'] = 100, 		['type'] = 'item', 		['image'] = 'beak_owlf.png', 				['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	  ['combinable'] = nil,		['level'] = 0,  ['description'] = 'Owl beak.'},    
    ['beak_ravenf'] 		    = {['name'] = 'beak_ravenf', 		['label'] = 'Raven beak',           ['weight'] = 100, 		['type'] = 'item', 		['image'] = 'beak_ravenf.png', 				['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	  ['combinable'] = nil,		['level'] = 0,  ['description'] = 'Raven beak.'},   
    ['beak_duckf'] 			    = {['name'] = 'beak_duckf', 		['label'] = 'Duck beak',            ['weight'] = 100, 		['type'] = 'item', 		['image'] = 'beak_duckf.png', 				['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	  ['combinable'] = nil,		['level'] = 0,  ['description'] = 'Duck beak.'},   
    ['beak_vulturef'] 		    = {['name'] = 'beak_vulturef', 		['label'] = 'Vulture beak',         ['weight'] = 100, 		['type'] = 'item', 		['image'] = 'beak_vulturef.png', 		    ['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	  ['combinable'] = nil,		['level'] = 0,  ['description'] = 'Vulture beak.'},  

 -- cooking MEATS RAW
    ['small_raw_meat']          = {['name'] = 'small_raw_meat',     ['label'] = 'Small Raw Meat',       ['weight'] = 50,  ['type'] = 'item', ['image'] = 'small_raw_meat.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Small meat ready for cooking'},   
    ['raw_meat']                = {['name'] = 'raw_meat',           ['label'] = 'Raw Meat',             ['weight'] = 50,  ['type'] = 'item', ['image'] = 'raw_meat.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Raw Meat ready for cooking'},
    ['large_raw_meat']          = {['name'] = 'large_raw_meat',     ['label'] = 'Large Raw Meat',       ['weight'] = 50,  ['type'] = 'item', ['image'] = 'large_raw_meat.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Large meat ready for cooking'},
-- COOKED MEATS
    ['small_cooked_meat']       = {['name'] = 'small_cooked_meat',  ['label'] = 'Small Steak',          ['weight'] = 50,  ['type'] = 'item', ['image'] = 'small_cooked_meat.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Should feed me a little bit',["created"] = nil, ["decay"] = 1.0, ["delete"] = true},
    ['cooked_meat']             = {['name'] = 'cooked_meat',        ['label'] = 'Meat Steak',           ['weight'] = 50,  ['type'] = 'item', ['image'] = 'cooked_meat.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Should be sustain me',["created"] = nil, ["decay"] = 1.0, ["delete"] = true},
    ['large_cooked_meat']       = {['name'] = 'large_cooked_meat',  ['label'] = 'Large Steak',          ['weight'] = 50,  ['type'] = 'item', ['image'] = 'large_cooked_meat.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good for eating!',["created"] = nil, ["decay"] = 1.0, ["delete"] = true},
    
-- BIRD MEATS
    ['small_bird_meat']         = {['name'] = 'small_bird_meat',    ['label'] = 'Small Bird Meat',      ['weight'] = 50,  ['type'] = 'item', ['image'] = 'small_bird_meat.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Small meat ready for cooking'},   
    ['bird_meat']               = {['name'] = 'bird_meat',          ['label'] = 'Raw Bird Meat',        ['weight'] = 50,  ['type'] = 'item', ['image'] = 'bird_meat.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Raw Meat ready for cooking'},
    ['large_bird_meat']         = {['name'] = 'large_bird_meat',    ['label'] = 'Large Bird Meat',      ['weight'] = 50,  ['type'] = 'item', ['image'] = 'large_bird_meat.png',    ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Large meat ready for cooking'},
-- COOKED BIRD MEATS
    ['cookedsmall_bird_meat']   = {['name'] = 'cookedsmall_bird_meat',  ['label'] = 'Chick Drum Sticks', ['weight'] = 50,  ['type'] = 'item', ['image'] = 'cookedsmall_bird_meat.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Should feed me a little bit',["created"] = nil, ["decay"] = 1.0, ["delete"] = true},
    ['cookedbird_meat']         = {['name'] = 'cookedbird_meat',        ['label'] = 'Chicken Wings',     ['weight'] = 50,  ['type'] = 'item', ['image'] = 'cookedbird_meat.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Should be sustain me',["created"] = nil, ["decay"] = 1.0, ["delete"] = true},
    ['cookedlarge_bird_meat']   = {['name'] = 'cookedlarge_bird_meat',  ['label'] = 'Whole Chicken',    ['weight'] = 50,  ['type'] = 'item', ['image'] = 'cookedlarge_bird_meat.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Good for eating!',["created"] = nil, ["decay"] = 1.0, ["delete"] = true},
-- added
    ['rat_c']                   = {['name'] = 'rat_c',              ['label'] = 'Dead Rat',             ['weight'] = 50,        ['type'] = 'item',      ['image'] = 'rat_c.png',                    ['unique'] = false,     ['useable'] = true,     ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Dead rat gross!'},
    ['heart_chicken']           = {['name'] = 'heart_chicken',      ['label'] = 'Chicken Heart',        ['weight'] = 50,        ['type'] = 'item',      ['image'] = 'heart_chicken.png',            ['unique'] = false,     ['useable'] = true,     ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Chicken heart'},
    ['fat']                     = {['name'] = 'cookedlarge_bird_meat',  ['label'] = 'Whole Chicken',    ['weight'] = 50,        ['type'] = 'item',      ['image'] = 'cookedlarge_bird_meat.png',    ['unique'] = false,     ['useable'] = true,     ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Animal fat!'},
    ['heart_bear']              = {['name'] = 'heart_bear',         ['label'] = 'Bear heart',           ['weight'] = 50,        ['type'] = 'item',      ['image'] = 'heart_bear.png',               ['unique'] = false,     ['useable'] = true,     ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Heart of a bear!'},
    ['heart_wolf']              = {['name'] = 'heart_wolf',         ['label'] = 'Wolf Heart',           ['weight'] = 50,        ['type'] = 'item',      ['image'] = 'heart_wolf.png',               ['unique'] = false,     ['useable'] = true,     ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Wolf Heart!'},
    ['heart_deer']              = {['name'] = 'heart_deer',         ['label'] = 'Deer Heart',           ['weight'] = 50,        ['type'] = 'item',      ['image'] = 'heart_deer.png',               ['unique'] = false,     ['useable'] = true,     ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Dear Heart!'},
    ['sinew']                   = {['name'] = 'sinew',              ['label'] = 'Sinew',                ['weight'] = 50,         ['type'] = 'item',     ['image'] = 'sinew.png',                    ['unique'] = false,     ['useable'] = true,     ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Sinew!'},
